version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: /Project_Practices/ticketing-project-security-part-0
    steps:
      - checkout
      - run: mkdir -p /Project_Practices/ticketing-project-security-part-0
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /Project_Practices/ticketing-project-security-part-0
          paths: .
  docker-image-and-publish:
    machine: true
    steps:
      - attach_workspace:
          at: /Project_Practices/ticketing-project-security-part-0
      - run: ls -a /Project_Practices/ticketing-project-security-part-0
      - run:
          name: Create Docker image and push to ECR
          command: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 897184280640.dkr.ecr.eu-north-1.amazonaws.com && docker build -t tikcetingapp /tmp/workspace && docker tag tikcetingapp:latest 897184280640.dkr.ecr.eu-north-1.amazonaws.com/tikcetingapp:latest && docker push 897184280640.dkr.ecr.eu-north-1.amazonaws.com/tikcetingapp:latest
  deploy-job:
    docker:
      #specify the version you desire here
      - image: circleci/node:10.0.0
    steps:
      - run:
          name: Execute Deployment Script
          command: |
            ssh -o "StrictHostKeyChecking=no" ec2-16-171-224-57.eu-north-1.compute.amazonaws.com <<'ENDSSH'
            /bin/bash bin/deploy_image.sh
            docker ps
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - docker-image-and-publish:
          requires:
            - build
      - deploy-job:
          requires:
            - docker-image-and-publish